config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get 'contacts', to: 'welcome#contacts'

  resources :categories do
    resources :projects
    get 'works', to: 'categories#works', on: :member
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
        can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_attached_file :fon, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :fon, content_type: /\Aimage\/.*\Z/

  has_many :projects, dependent: :destroy

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_attached_file :picture, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  belongs_to :category

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include CanCan::ControllerAdditions
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  load_resource class: 'Category'

  def index

  end

  def new

  end

  def create
    @category = Category.create(resource_params)
    if @category.save!
      redirect_to categories_path, notice: "Категория '#{@category.name}' была успешно создана"
    else
      render action: :new
    end
  end

  def edit

  end

  def update
    @category.update(resource_params)
    if @category.save!
      redirect_to categories_path, notice: "Категория '#{@category.name}' была успешно изменёна"
    else
      render action: :edit
    end
  end

  def works
    @projects = @category.projects
  end

  def destroy
    @category.destroy!
    redirect_to categories_path, notice: 'Категория была удалена'
  end

  def resource_params
    params.require(:category).permit(:name, :description, :created_at, :updated_at, :fon)
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_resource :category, class: 'Category'
  load_resource through: :category, class: 'Project'

  def index

  end

  def new

  end

  def create
    @project = @category.projects.create(resource_params)
    if @project.save!
      redirect_to category_projects_path(@category), notice: "Проект '#{@project.name}' был успешно создан"
    else
      render action: :new
    end
  end

  def edit

  end

  def update
    @project.update(resource_params)
    if @project.save!
      redirect_to category_projects_path(@category), notice: "Проект '#{@project.name}' был успешно изменён"
    else
      render action: :edit
    end
  end

  def destroy
    @project.destroy!
    redirect_to category_projects_path, notice: 'Проект был удалён'
  end

  def resource_params
    params.require(:project).permit(:name, :description, :created_at, :updated_at, :picture, :category_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @categories = Category.all
  end

  def contacts
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, url: url do |f| %>
  <div>
      <%= f.label :name, class: '' %>
      <div class="form">
          <%= f.text_field :name, class: '' %>
      </div>
  </div>

  <div>
      <%= f.label :description, class: '' %>
      <div class="form">
          <div>
              <%= f.text_area :description, rows: 10 %>
          </div>
      </div>
  </div>

  <fieldset>
      <legend>Фоновое изображение</legend>
        <div>
            <% if f.object.fon.url != '/images/original/missing.png' %>
              <%= image_tag f.object.fon.url(:medium) %>
            <% else %>
              <%= f.file_field :fon %>
            <% end %>
        </div>

  </fieldset>


  <br>
  <div class="col col-sm-10 col-sm-offset-2">
      <%= f.submit 'Сохранить', class: 'button small' %> или <%= link_to 'Отмена', categories_path, class: 'button small secondary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h3>
    Редактирование категории
    <small class="nowrap"><%= @category.name %></small>
</h3>

<%= render partial: 'form',
           locals: { url: category_path(@category) } %>

app/views/categories/index.html.erb
<h3>Категории</h3>

<%= link_to new_category_path, class: 'button small info' do %>
  <i class="fi-plus"></i> Создать новую категорию
<% end %>

<% if @categories.any? %>
  <table style="width: 100%;">
      <thead>
      <tr>
          <th>#</th>
          <th>Категория</th>
          <th>Количество проектов</th>
          <th></th>
      </tr>
      </thead>
      <tbody>
      <% @categories.each do |category| %>
        <tr>
            <td><%= category.id %></td>
            <td>
                <p><%= category.name %></p>
                <p><%= category.description %><p>
            </td>
            <td>
                <%= category.projects.length %>
                <br><br>
                <%= link_to category_projects_path(category), class: 'button tiny' do %>
                  <%= fa_icon 'plus' %> Добавить
                <% end %>
            </td>
            <td>
                <%= link_to edit_category_path(category), class: 'button normal', title: 'Редактировать' do %>
                  <%= fa_icon 'wrench' %>
                <% end %>
                <%= link_to category_path(category), method: :delete, class: 'button danger', title: 'Удалить', data: {confirm: 'Вы уверены?'} do %>
                  <%= fa_icon 'remove' %>
                <% end %>
            </td>
        </tr>
      <% end %>
      </tbody>
  </table>
<% else %>
  <p class="information">Пока не было создано ни одной категории</p>
<% end %>

app/views/categories/new.html.erb
<h3>
    Создать новую категорию
</h3>

<%= render partial: 'form',
           locals: { url: categories_path } %>

app/views/categories/works.html.erb
<h3>Проекты <small><%= @category.name %></small></h3>

<div id="project">
  <div class="fotorama"
       data-nav="thumbs" data-transition="crossfade">
      <% @projects.each do |project| %>
        <a href="<%= project.picture.url %>"><%= image_tag project.picture.url(:thumb) %></a>
      <% end %>
  </div>
</div>

<div id="explanation">
  <% @projects.each do |project| %>
    <div class="explain" data-value="<%= project.picture.url %>" style="display: none;">
      <%= project.name %>
      <p><%= project.description %></p>
    </div>
  <% end %>
</div>

<p class="text-right"><%= link_to 'Посмотреть другие работы', root_path, class: 'link' %></p>

<script>
  $('.fotorama').on('fotorama:show', function (e, fotorama) {
    $('.explain').hide();
    $('.explain[data-value="' + fotorama.activeFrame.img + '"]').show();

  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grafema</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300&subset=latin,cyrillic,cyrillic-ext' rel='stylesheet' type='text/css'>
</head>
<body>

<div class="header">
    <%= link_to root_path do %>
      <%= image_tag :logo %>
      <hgroup>
          <h1>Ольга Яковлева<br><small>Дизайнер</small></h1>

      </hgroup>
    <% end %>
    <nav>
        <a href="#">Специальные предложения</a>
        <%= link_to 'Контакты', contacts_path %>
        <a href="#">Оформление мероприятий</a>
    </nav>
</div>

<div class="content">
    <%= yield %>
</div>

<div class="footer">

</div>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, url: url do |f| %>
  <div>
      <%= f.label :name, class: '' %>
      <div class="form">
          <%= f.text_field :name, class: '' %>
      </div>
  </div>

  <div>
      <%= f.label :description, class: '' %>
      <div class="form">
          <div>
              <%= f.text_area :description, rows: 10 %>
          </div>
      </div>
  </div>

  <div>
      <%= label_tag :cat, 'Категория' %>
      <div class="form">
          <div>
              <%= text_field_tag :cat, @category.name, disabled: true %>
          </div>
      </div>
  </div>

  <fieldset>
      <legend>Изображение</legend>
        <div>
            <% if f.object.picture.url != '/images/original/missing.png' %>
              <%= image_tag f.object.picture.url(:thumb) %>
              <label style="float: right">Изменить изображение: <%= f.file_field :picture %></label>
            <% else %>
              <%= f.file_field :picture %>
            <% end %>
        </div>

  </fieldset>


  <br>
  <div class="col col-sm-10 col-sm-offset-2">
      <%= f.submit 'Сохранить', class: 'button small' %> или <%= link_to 'Отмена', categories_path, class: 'button small secondary' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h3>
    Редактирование проекта "<%= @project.name %>"
    <small class="nowrap"><%= @category.name %></small>
</h3>

<%= render partial: 'form',
           locals: { url: category_project_path(@category, @project) } %>

app/views/projects/index.html.erb
<h3>Проекты <small><%= @category.name %></small></h3>

<%= link_to new_category_project_path(@category), class: 'button small info' do %>
  <i class="fi-plus"></i> Создать новый проект
<% end %>

<% if @projects.any? %>
  <table style="width: 100%;">
      <thead>
      <tr>
          <th>#</th>
          <th>Проект</th>
          <th>Изображение</th>
          <th></th>
      </tr>
      </thead>
      <tbody>
      <% @projects.each do |project| %>
        <tr>
            <td><%= project.id %></td>
            <td><%= project.name %>
            </td>
            <td><%= image_tag project.picture.url(:thumb) %></td>
            <td>
                <%= link_to edit_category_project_path(@category, project), class: 'button normal', title: 'Редактировать' do %>
                  <%= fa_icon 'wrench' %>
                <% end %>
                <%= link_to category_project_path(@category, project), method: :delete, class: 'button danger', title: 'Удалить', data: {confirm: 'Вы уверены?'} do %>
                  <%= fa_icon 'remove' %>
                <% end %>
            </td>
        </tr>
      <% end %>
      </tbody>
  </table>
<% else %>
  <p class="information">Пока не было создано ни одного проекта в категории "<%= @category.name %>"</p>
<% end %>

app/views/projects/new.html.erb
<h3>
    Создать новый проект
    <small><%= @category.name %></small>
</h3>

<%= render partial: 'form',
           locals: { url: category_projects_path(@category) } %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<% if @categories.any? %>

  <ul class="thumb">
  <% @categories.each do |category| %>
    <li>
        <%= link_to works_category_path(category) do %>
          <%= image_tag category.fon.url %>
          <div class="mask"> <div class="details"><%= category.name %></div></div>
        <% end %>
    </li>
  <% end %>
  </ul>

<% end %>